/**
 * Couche de compatibilité globale Lucide → Phosphor.
 *
 * Les composants de Gleba gardent leurs imports historiques depuis
 * `lucide-react`, redirigés ici par tsconfig. Cela garantit qu'un seul pack
 * d'icônes est rendu dans toute l'application et rend le test réversible.
 */
import type { Icon } from "@phosphor-icons/react"

export * from "@phosphor-icons/react/ssr"

export {
  Pulse as Activity,
  WarningCircle as AlertCircle,
  Warning as AlertTriangle,
  AppleLogo as Apple,
  DownloadSimple as ArrowDownToLine,
  SortAscending as ArrowDownWideNarrow,
  ArrowsDownUp as ArrowUpDown,
  ChartBar as BarChart3,
  Grains as Bean,
  Cow as Beef,
  Books as BookCopy,
  Robot as Bot,
  Cube as Box,
  Stack as Boxes,
  Buildings as Building2,
  CalendarDots as CalendarClock,
  CalendarBlank as CalendarDays,
  CalendarPlus as CalendarRange,
  Checks as CheckCheck,
  CheckCircle as CheckCircle2,
  Cherries as Cherry,
  CaretDown as ChevronDown,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  CaretUp as ChevronUp,
  CaretDoubleRight as ChevronsRight,
  CaretUpDown as ChevronsUpDown,
  CheckCircle as CircleCheck,
  ListChecks as ClipboardCheck,
  Clipboard as ClipboardList,
  Clock as Clock3,
  CloudSlash as CloudOff,
  Drop as Droplet,
  Drop as Droplets,
  PencilSimple as Edit,
  Pencil as Edit2,
  CurrencyEur as Euro,
  ArrowSquareOut as ExternalLink,
  EyeSlash as EyeOff,
  FacebookLogo as Facebook,
  Wall as Fence,
  FileArrowDown as FileDown,
  FileCsv as FileSpreadsheet,
  Files as FileStack,
  Flask as FlaskConical,
  Funnel as Filter,
  Flower as Flower2,
  GithubLogo as Github,
  GlobeHemisphereWest as Globe2,
  SquaresFour as Grid3X3,
  Heartbeat as HeartPulse,
  Question as HelpCircle,
  ClockCounterClockwise as History,
  House as Home,
  ImageSquare as ImagePlus,
  InstagramLogo as Instagram,
  StackSimple as Layers,
  Gauge as LayoutDashboard,
  GridFour as LayoutGrid,
  ChartLine as LineChart,
  ListBullets as ListTodo,
  SpinnerGap as Loader2,
  CrosshairSimple as LocateFixed,
  SignIn as LogIn,
  SignOut as LogOut,
  Envelope as Mail,
  SealCheck as MailCheck,
  MapTrifold as Map,
  ArrowsOut as Maximize2,
  ChatCircle as MessageCircle,
  ChatText as MessageSquare,
  ChatCircleDots as MessageSquarePlus,
  FlagBanner as Milestone,
  PintGlass as Milk,
  ArrowsIn as Minimize2,
  DotsThree as MoreHorizontal,
  Mountains as Mountain,
  ArrowsOutCardinal as Move,
  ArrowRight as MoveRight,
  SidebarSimple as PanelLeftClose,
  SidebarSimple as PanelLeftOpen,
  Confetti as PartyPopper,
  PenNib as PenTool,
  ChartPie as PieChart,
  ArrowCounterClockwise as RefreshCw,
  ArrowCounterClockwise as RotateCcw,
  ArrowClockwise as RotateCw,
  Path as Route,
  BowlFood as Salad,
  Broadcast as Satellite,
  FloppyDisk as Save,
  Scales as Scale,
  Scan as ScanLine,
  MagnifyingGlass as Search,
  PaperPlaneTilt as Send,
  Gear as Settings,
  ShareNetwork as Share2,
  ShieldWarning as ShieldAlert,
  ShieldSlash as ShieldOff,
  Plant as Shrub,
  Sparkle as Sparkles,
  SprayBottle as SprayCan,
  DeviceMobileSpeaker as SmartphoneNfc,
  Plant as Sprout,
  Storefront as Store,
  Tag as Tags,
  Trash as Trash2,
  Tree as TreeDeciduous,
  TreeEvergreen as TreePine,
  Tree as Trees,
  TrendDown as TrendingDown,
  TrendUp as TrendingUp,
  UserGear as UserCog,
  UserMinus as UserX,
  UsersThree as Users2,
  MagicWand as Wand2,
  Barbell as Weight,
  Grains as Wheat,
  WifiHigh as Wifi,
  Lightning as Zap,
  MagnifyingGlassPlus as ZoomIn,
  MagnifyingGlassMinus as ZoomOut,
} from "@phosphor-icons/react/ssr"

export type LucideIcon = Icon
